In [71]:
# Importing Pandas and Numpy
import pandas as pd
import numpy as ny

In [72]:
#Uploading the CSV FILE 
data = pd.read_csv("JC-202509-citibike-tripdata.csv")

In [73]:
# Top 5 Rows
data.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,3AAD1E1BCB6B326B,electric_bike,2025-09-04 08:36:52.378,2025-09-04 08:47:21.064,Lincoln Park,JC053,Dey St,JC065,40.724605,-74.078406,40.737711,-74.066921,casual
1,EC348BE3649505F6,electric_bike,2025-09-08 18:00:44.089,2025-09-08 18:18:48.698,Exchange Pl,JC116,Dey St,JC065,40.716366,-74.034344,40.737711,-74.066921,member
2,6639ACBA00F4DC07,classic_bike,2025-09-06 08:59:06.165,2025-09-06 14:27:30.692,Union St & Bergen Ave,JC122,Dey St,JC065,40.715750,-74.078870,40.737711,-74.066921,member
3,A10A50B94E43F61E,classic_bike,2025-09-08 18:11:33.185,2025-09-08 18:17:06.671,Bergen Ave & Sip Ave,JC109,Dey St,JC065,40.731009,-74.064437,40.737711,-74.066921,member
4,56D1E808E38A2034,electric_bike,2025-09-24 17:39:37.945,2025-09-24 18:01:08.535,Exchange Pl,JC116,Dey St,JC065,40.716366,-74.034344,40.737711,-74.066921,member

In [74]:
#Information regarding the Columns in the Table
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 116071 entries, 0 to 116070
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             116071 non-null  str
 1   rideable_type       116071 non-null  str
 2   started_at          116071 non-null  str
 3   ended_at            116071 non-null  str
 4   start_station_name  116071 non-null  str
 5   start_station_id    116071 non-null  str
 6   end_station_name    115710 non-null  str
 7   end_station_id      115584 non-null  str
 8   start_lat           116071 non-null  float64
 9   start_lng           116071 non-null  float64
 10  end_lat             115584 non-null  float64
 11  end_lng             115584 non-null  float64
 12  member_casual       116071 non-null  str
dtypes: float64(4), str(9)
memory usage: 11.5 MB

In [75]:
#Description
data.describe()

           start_lat      start_lng        end_lat        end_lng
count  116071.000000  116071.000000  115584.000000  115584.000000
mean       40.731919     -74.040784      40.731921     -74.040494
std         0.012288       0.012589       0.012377       0.012796
min        40.704503     -74.093680      40.668132     -74.093680
25%        40.721124     -74.046305      40.721124     -74.045953
50%        40.734961     -74.038051      40.734961     -74.037977
75%        40.742258     -74.030970      40.742258     -74.030970
max        40.754530     -74.024020      40.886300     -73.887810

In [76]:
a = 0
b = 0
for x in data.columns:
    c= 0 
    b = b +1
    if "_" in x and x.islower():
        c = c+1
    if c == 1:
        a= a+1 
if a == b:
    print("Column Labels are in Snake Format, and are as follows:")
else:
    print("Column Labels are not in Snake Format, and are as follows:")
data.columns

Column Labels are in Snake Format, and are as follows:

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str')

In [77]:
#Checking for Null Values
data.isnull().sum()

ride_id                 0
rideable_type           0
started_at              0
ended_at                0
start_station_name      0
start_station_id        0
end_station_name      361
end_station_id        487
start_lat               0
start_lng               0
end_lat               487
end_lng               487
member_casual           0
dtype: int64

In [78]:
#Checking for Duplicate Rows, If found then the duplicates need to be Dropped
data.duplicated().sum()

np.int64(0)

In [79]:
#Checking for Duplicate Ride ID, If found then the duplicates need to be Dropped
data.duplicated(subset=['ride_id'])

0         False
1         False
2         False
3         False
4         False
          ...
116066    False
116067    False
116068    False
116069    False
116070    False
Length: 116071, dtype: bool

In [80]:
#Converting the Stating and Ending Time to DateTime Data Type
data["started_at"] = pd.to_datetime(data["started_at"])
data["ended_at"] = pd.to_datetime(data["ended_at"])
data[["started_at","ended_at"]].dtypes

started_at    datetime64[us]
ended_at      datetime64[us]
dtype: object

In [81]:
#Checking and removing those rides which from different months may have been existing in the data
(data["started_at"].dt.month != 9).sum()
data = data.drop(data[data["started_at"].dt.month != 9].index)

In [82]:
# Adding the end_station id for those rides which have the end_station_name but not the end_station_id. 
# This is done by creating a lookup table of station names and their corresponding station ids, 
# and then using that lookup table to fill in the missing end_station_ids.

start_lookup = (
    data[["start_station_id", "start_station_name"]]
    .dropna()
    .drop_duplicates()
)
end_lookup = (
    data[["end_station_id", "end_station_name"]]
    .dropna()
    .drop_duplicates()
    .rename(columns={"end_station_id": "start_station_id",
                     "end_station_name": "start_station_name"})
)
station_lookup = (
    pd.concat([start_lookup, end_lookup])
    .drop_duplicates()
    .set_index("start_station_name")["start_station_id"]
)
 
missing_id_mask = data["end_station_name"].notna() & data["end_station_id"].isna()
missing_before = missing_id_mask.sum()
data.loc[missing_id_mask, "end_station_id"] = (
    data.loc[missing_id_mask, "end_station_name"].map(station_lookup)
)
missing_after = (data["end_station_name"].notna() & data["end_station_id"].isna()).sum()
recovered = missing_before - missing_after
print(f"Recovered station IDs for {recovered} rides.")

Recovered station IDs for 126 rides.

In [83]:
# Calculating the Duration of Each Trip in Minute
data["duration_min"] = ((data["ended_at"] - data["started_at"]).dt.total_seconds()/60).round(2)
data["duration_min"]

0          10.48
1          18.08
2         328.41
3           5.56
4          21.51
           ...
116066      2.50
116067      9.67
116068      3.11
116069      3.95
116070      2.26
Name: duration_min, Length: 116055, dtype: float64

In [84]:
#Getting a Idea about the duration of the Rides
print(data['duration_min'].describe(percentiles=[.25, .5, .75, .85,.90]))

count    116055.000000
mean         10.744153
std          40.678686
min           1.010000
25%           4.200000
50%           6.470000
75%          10.390000
85%          13.840000
90%          17.230000
max        1499.950000
Name: duration_min, dtype: float64

In [85]:
#Checking if the Duration is Negative or Equal to Zero (Which is practically not possible)
(data["duration_min"]<=0).sum()

np.int64(0)

In [86]:
#Adding a column in the Dataframe which would be indicator to if the ride was longer than usual
duration_outlier_cutoff = 120 # 2 Hours as the Average Duration btw the fartest points in Jersey City using bike is around 45 mins (Source: )
data['duration_outlier']= data['duration_min'] > duration_outlier_cutoff
outlier_rides = data['duration_outlier'].sum()

In [87]:
# Get unique start stations and their count
unique_start_stations = data['start_station_name'].unique().tolist()
unique_start_stations_id = data['start_station_id'].unique().tolist()
print("Start Stations:", sorted(unique_start_stations))
print("Start Station IDs:", sorted(unique_start_stations_id))
print("Count of Start Stations:", len(unique_start_stations))

# Get unique end stations and their count
unique_end_stations = data['end_station_name'].unique().tolist()
unique_end_stations_id = data['end_station_id'].unique().tolist()
print("End Stations:", unique_end_stations)
print("End Station IDs:", unique_end_stations_id)
print("Count of End Stations:", len(unique_end_stations))

# Convert station lists to sets for comparison
start_stations = set(data['start_station_name'].dropna())
start_stations_id = set(data['start_station_id'].dropna())
end_stations = set(data['end_station_name'].dropna())
end_stations_id = set(data['end_station_id'].dropna())

# Stations that appear as both start and end stations
common_stations = start_stations.intersection(end_stations)
common_stations_id = set(data['start_station_id']).intersection(set(data['end_station_id']))

print("Stations appearing in both Start and End:")
print(sorted(common_stations))
print("Count:", len(common_stations))
print("Common Station IDs:", sorted(common_stations_id))

# Stations that appear only as start stations
start_only = start_stations - end_stations
start_only_id = set(data['start_station_id']) - set(data['end_station_id'])

print("Start Only Stations:")
print(sorted(start_only))
print("Count:", len(start_only))
print("Start Only Station IDs:", sorted(start_only_id))

# Stations that appear only as end stations
end_only = end_stations - start_stations
end_only_id = set(data['end_station_id']) - set(data['start_station_id'])

print("End Only Stations:")
print(sorted(end_only))
print("Count:", len(end_only))
print("End Only Station IDs:", end_only_id)

# Summary statistics
print(f"Start Stations: {len(start_stations)}")
print(f"End Stations: {len(end_stations)}")
print(f"Common Stations: {len(common_stations)}")
print(f"Start Only Stations: {len(start_only)}")
print(f"End Only Stations: {len(end_only)}")

Start Stations: ['11 St & Washington St', '12 St & Sinatra Dr N', '14 St Ferry - 14 St & Shipyard Ln', '2 St & Park Ave', '4 St & Grand St', '4 St & River St', '5 Corners Library', '6 St & Grand St', '7 St & Monroe St', '8 St & Washington St', '9 St HBLR - Jackson St & 8 St', 'Adams St & 12 St', 'Adams St & 2 St', 'Arlington Ave & Bramhall Ave', 'Arlington Ave & Wilkinson Ave', 'Astor Place', 'Baldwin at Montgomery', 'Bergen Ave', 'Bergen Ave & Sip Ave', 'Bergen Ave & Stegman St', 'Bloomfield St & 15 St', 'Brunswick & 6th', 'Brunswick St', 'Carteret Ave & Arlington Ave', 'Christ Hospital', 'Church Sq Park - 5 St & Park Ave', 'City Hall', 'City Hall - Washington St & 1 St', 'Claremont Ave & JFK Blvd', 'Clinton St & 7 St', 'Clinton St & Newark St', 'Columbus Drive', 'Columbus Park - Clinton St & 9 St', 'Communipaw & Berry Lane', 'Communipaw Ave & Pacific Ave', 'Dey St', 'Dixon Mills', 'Dr. Lena Edwards Park', 'Essex Light Rail', 'Exchange Pl', 'Fairmount Ave', 'Garfield Light Rail', 'Glenwood Ave', 'Grand St', 'Grant Ave & MLK Dr', 'Grove St PATH', 'Hamilton Park', 'Harborside', 'Heights Elevator', 'Hilltop', 'Hoboken Ave at Monmouth St', 'Hoboken Terminal - Hudson St & Hudson Pl', 'JC Medical Center', 'Jackson Square', 'Jersey & 3rd', 'Jersey & 6th St', 'Journal Square', 'Lafayette Park', 'Leonard Gordon Park', 'Liberty Light Rail', 'Lincoln Park', 'MLK Dr & Bramhall Ave', 'Madison St & 1 St', 'Mama Johnson Field - 4 St & Jackson St', 'Manila & 1st', 'Marin Light Rail', 'Marshall St & 2 St', 'McGinley Square', 'Monmouth & 6th', 'Monroe St & 11 St', 'Montgomery St', 'Morris Canal', 'Newark Ave', 'Newark St & Washington St', 'Newport PATH', 'Newport Pkwy', 'Oakland Ave', 'Paulus Hook', 'Pershing Field', 'River St & 1 St', 'River St & Newark St', 'Riverview Park', 'South Waterfront Walkway - Sinatra Dr & 1 St', 'Southwest Park - Jackson St & Observer Hwy', 'Stevens - River Ter & 6 St', 'Union St', 'Union St & Bergen Ave', 'Van Vorst Park', 'Warren St', 'Washington St', 'West Side Ave & Stegman Pkwy', 'West Side Ave Light Rail', 'Willow Ave & 12 St', 'York St & Marin Blvd']
Start Station IDs: ['HB101', 'HB103', 'HB105', 'HB106', 'HB201', 'HB202', 'HB203', 'HB301', 'HB302', 'HB303', 'HB304', 'HB305', 'HB401', 'HB402', 'HB404', 'HB407', 'HB408', 'HB409', 'HB501', 'HB502', 'HB505', 'HB508', 'HB601', 'HB602', 'HB603', 'HB608', 'HB609', 'HB610', 'HB611', 'HB612', 'JC002', 'JC003', 'JC006', 'JC008', 'JC009', 'JC013', 'JC014', 'JC018', 'JC019', 'JC020', 'JC022', 'JC023', 'JC024', 'JC027', 'JC032', 'JC034', 'JC035', 'JC038', 'JC051', 'JC052', 'JC053', 'JC055', 'JC057', 'JC059', 'JC063', 'JC065', 'JC066', 'JC072', 'JC074', 'JC075', 'JC076', 'JC077', 'JC078', 'JC080', 'JC081', 'JC082', 'JC084', 'JC093', 'JC094', 'JC095', 'JC097', 'JC098', 'JC099', 'JC102', 'JC103', 'JC104', 'JC105', 'JC107', 'JC108', 'JC109', 'JC110', 'JC115', 'JC116', 'JC117', 'JC118', 'JC119', 'JC120', 'JC121', 'JC122', 'JC123', 'JC124', 'JC125', 'JC127', 'JC131']
Count of Start Stations: 94
End Stations: ['Dey St', 'Pershing Field', 'E 40 St & 5 Ave', 'Christ Hospital', 'Hoboken Ave at Monmouth St', 'North Moore St & Greenwich St', 'MLK Dr & Bramhall Ave', 'Jackson Square', 'West Side Ave & Stegman Pkwy', 'Marshall St & 2 St', 'Adams St & 12 St', 'Communipaw & Berry Lane', 'Mama Johnson Field - 4 St & Jackson St', 'Stevens - River Ter & 6 St', 'West Side Ave Light Rail', 'Brunswick & 6th', 'Hilltop', 'Claremont Ave & JFK Blvd', 'Leonard Gordon Park', 'Grant Ave & MLK Dr', 'E 33 St & 5 Ave', 'Glenwood Ave', 'Paulus Hook', 'Journal Square', 'West St & Chambers St', 'Union St & Bergen Ave', '6 St & Grand St', 'Heights Elevator', 'Clinton St & Newark St', 'Grand St', 'Bleecker St & Crosby St', 'Greene St & Prince St', 'Union St', '2 St & Park Ave', '3 St & Prospect Park West', 'South Waterfront Walkway - Sinatra Dr & 1 St', 'W 37 St & 5 Ave', 'Liberty Light Rail', 'Carteret Ave & Arlington Ave', 'Newark Ave', 'Arlington Ave & Bramhall Ave', 'Greenwich St & Hubert St', 'Amsterdam Ave & W 66 St', 'Murray St & Greenwich St', 'Baldwin at Montgomery', '5 Ave & E 30 St', 'Madison St & 1 St', 'W 51 St & 7 Ave', 'Broadway & W 38 St', 'Broadway & W 25 St', '10 Ave & W 14 St', 'Bus Slip & State St', 'LaGuardia Pl & W 3 St', 'W 16 St & The High Line', 'W 27 St & 6 Ave', 'Washington St & Laight St', '9 Ave & W 33 St', 'William St & Pine St', 'Reade St & Broadway', 'Lawrence St & Willoughby St', 'W Broadway & W Houston St', 'Jersey & 3rd', 'W 35 St & 9 Ave', 'W 37 St & Broadway', 'Hamilton Park', 'Garfield Light Rail', 'Bergen Ave & Sip Ave', 'Vesey St & Greenwich St', 'E 15 St & 5 Ave', 'W 20 St & 8 Ave', '9 St HBLR - Jackson St & 8 St', 'Hudson St & W 13 St', 'Dixon Mills', 'Adams St & 2 St', 'E 55 St & 2 Ave', 'W 34 St & 11 Ave', 'University Pl & E 8 St', 'W 37 St & 10 Ave', 'Park Ave & E 42 St', '12 St & Sinatra Dr N', 'South St & Gouverneur Ln', 'Greenwich Ave & 8 Ave', 'E 1 St & 1 Ave', '6 Ave & W 34 St', 'Cleveland Pl & Spring St', 'Mercer St & Bleecker St', 'Church St & Worth St', 'Hudson Blvd W & W 36 St', 'W Broadway & Spring St', 'Watts St & Greenwich St', '3 Ave & E 82 St', 'Broad St & Bridge St', 'Milton St & Franklin St', 'Pier 61 at Chelsea Piers', 'Broadway & Van Cortlandt Park S', 'Columbus Park - Clinton St & 9 St', '5 Corners Library', 'Lincoln Park', 'Mercer St & Spring St', 'E 40 St & Park Ave', 'E 43 St & Madison Ave', '9 Ave & W 18 St', 'Greenwich St & W Houston St', 'Broadway & 31 St', 'West Thames St', 'Jersey & 6th St', '2 Ave & E 125 St', 'Fulton St & Broadway', 'Broadway & Morris St', 'Washington St & Gansevoort St', 'University Pl & E 14 St', 'Broadway & W 48 St', 'W 54 St & 11 Ave', 'W 59 St & 10 Ave', 'Fairmount Ave', 'N 12 St & Bedford Ave', 'Spruce St & Nassau St', '8 Ave & W 38 St', '7 St & Monroe St', 'E 44 St & Lexington Ave', 'W 20 St & 5 Ave', 'E 5 St & Cooper Sq', 'Broadway & W 37 St', 'Hudson St & Reade St', 'E 50 St & Park Ave', 'Water St & Gouverneur Ln', 'E 16 St & 5 Ave', '12 Ave & W 40 St', 'E 16 St & Irving Pl', 'McGinley Square', 'Astor Place', 'Maiden Ln & Pearl St', 'Brunswick St', 'Jay St & Tech Pl', 'Morton St & Greenwich St', '3 Ave & E 71 St', 'Old Fulton St', 'Park Ave & E 41 St', 'Church Sq Park - 5 St & Park Ave', 'JC Medical Center', 'Morris Canal', 'Central Park S & 6 Ave', 'Leonard St & Church St', 'McKibbin St & Bogart St', 'Park Ave & E 40 St', 'Washington St', 'Hoboken Terminal - Hudson St & Hudson Pl', 'Arlington Ave & Wilkinson Ave', 'Newport PATH', 'Bergen Ave', 'Lafayette Park', '4 St & Grand St', 'Monmouth & 6th', 'Bergen Ave & Stegman St', 'Monroe St & 11 St', 'Communipaw Ave & Pacific Ave', 'E 19 St & 3 Ave', 'Bloomfield St & 15 St', 'Clinton St & 7 St', 'W 34 St & Hudson Blvd E', '8 Ave & W 16 St', 'City Hall', 'Essex Light Rail', 'Willow Ave & 12 St', 'Southwest Park - Jackson St & Observer Hwy', 'Dr. Lena Edwards Park', '14 St Ferry - 14 St & Shipyard Ln', 'York St & Marin Blvd', 'Van Vorst Park', 'Manila & 1st', 'Columbus Drive', 'Newport Pkwy', 'Warren St', 'Vesey Pl & River Terrace', 'Carmine St & 6 Ave', 'River Ter & Warren St', 'W 30 St & 10 Ave', 'Water St & Fletcher St', 'River St & Newark St', 'Harborside', 'Harrison St & Hudson St', 'MacDougal St & Prince St', 'West St & Liberty St', 'E 27 St & 1 Ave', 'Cliff St & Fulton St', 'Lafayette St & Jersey St', 'W 4 St & 7 Ave S', 'Grand St & Greene St', 'E 7 St & Ave C', 'River St & 1 St', 'Van Cortlandt Park S & Dickinson Ave', 'Spring St & Hudson St', 'Old Slip & South St', 'Fulton St & William St', '6 Ave & Broome St', 'N 15 St & Wythe Ave', 'Lafayette St & E 8 St', 'Laight St & Hudson St', 'Riverside Dr & W 82 St', 'E 26 St & 3 Ave', 'Christopher St & Greenwich St', '6 Ave & W 45 St', 'Pearl St & Whitehall St', 'Canal St & Rutgers St', 'Liberty St & Broadway', 'W 48 St &  Rockefeller Plaza', 'W 56 St & 6 Ave', 'Bridge St & Front St', 'Newark St & Washington St', 'City Hall - Washington St & 1 St', 'Exchange Pl', 'Riverview Park', 'Oakland Ave', nan, '8 Ave & W 31 St', 'Pier 40 - Hudson River Park', 'W 44 St & 5 Ave', 'Vesey St & Church St', 'Marin Light Rail', 'Grove St PATH', 'Varick St & Watts St', 'Montgomery St', '4 St & River St', '11 St & Washington St', '8 St & Washington St', '2 Ave & E 72 St', 'Broadway & W 58 St', 'E 88 St & 1 Ave', 'Lispenard St & Broadway', 'Washington Pl & 6 Ave', 'E 3 St & 1 Ave', 'Warren St & W Broadway', 'Division St & Bowery', 'Sigourney St & Columbia St', 'East End Ave & E 86 St', 'E 2 St & 2 Ave', 'W 42 St & 8 Ave', 'N 10 St & Berry St']
End Station IDs: ['JC065', 'JC024', '6474.11', 'JC034', 'JC105', '5470.12', 'JC121', 'JC063', 'JC131', 'HB408', 'HB610', 'JC084', 'HB404', 'HB602', 'JC124', 'JC081', 'JC019', 'JC125', 'JC080', 'JC107', '6322.01', 'JC094', 'JC002', 'JC103', '5329.03', 'JC122', 'HB302', 'JC059', 'HB409', 'JC102', '5679.08', '5602.06', 'JC051', 'HB608', '3865.05', 'HB103', '6398.06', 'JC052', 'JC123', 'JC032', 'JC120', '5470.10', '7149.05', '5288.12', 'JC020', '6248.08', 'HB402', '6779.07', '6560.15', '6173.08', '6157.04', '4889.06', '5721.14', '6233.05', '6215.07', '5509.02', '6492.08', '5065.12', '5247.10', '4596.09', '5644.05', 'JC074', '6569.09', '6441.06', 'JC009', 'JC119', 'JC109', '5216.07', '5947.06', '6224.05', 'HB305', '6115.06', 'JC076', 'HB407', '6650.07', '6578.01', '5755.14', '6611.02', '6432.09', 'HB201', '4953.04', '6072.06', '5593.01', '6364.10', '5492.05', '5679.05', '5359.13', '6611.07', '5569.06', '5578.02', '7154.10', '4962.08', '5752.07', '6233.04', '8879.02', 'HB501', 'JC018', 'JC053', '5532.01', '6432.11', '6551.11', '6190.08', '5730.08', '6789.08', '5114.06', 'JC027', '7648.16', '5175.08', '5033.01', '6039.06', '5905.14', '6708.04', '6955.05', '7023.04', 'JC093', '5450.04', '5137.10', '6526.05', 'HB304', '6464.09', '6098.02', '5712.12', '6441.02', '5359.10', '6659.10', '4993.15', '6022.04', '6765.01', '5938.11', 'JC055', 'JC077', '5065.10', 'JC023', '4710.06', '5772.05', '6960.12', '4903.08', '6432.08', 'HB601', 'JC110', 'JC072', '6876.04', '5359.11', '5059.02', '6432.15', 'JC098', 'HB101', 'JC127', 'JC066', 'JC095', 'JC078', 'HB301', 'JC075', 'JC108', 'HB508', 'JC118', '5938.01', 'HB203', 'HB303', '6535.04', '6072.11', 'JC003', 'JC038', 'HB505', 'HB401', 'JC117', 'HB202', 'JC097', 'JC035', 'JC082', 'JC014', 'JC008', 'JC006', '5297.02', '5763.03', '5368.03', '6459.07', '5024.10', 'HB106', 'JC104', '5400.05', '5687.04', '5184.08', '6004.06', '5065.14', '5561.06', '5880.02', '5500.02', '5545.01', 'HB609', '8859.03', '5653.12', '4993.13', '5137.11', '5610.09', '5520.09', '5788.13', '5539.06', '7388.10', '6089.11', '5847.01', '6593.15', '4962.09', '5303.08', '5105.01', '6626.11', '6809.07', '4968.03', 'HB612', 'HB105', 'JC116', 'JC057', 'JC022', nan, '6450.05', '5696.03', '6551.02', '5216.06', 'JC013', 'JC115', '5539.08', 'JC099', 'HB611', 'HB502', 'HB603', '6925.09', '6948.10', '7235.13', '5391.06', '5838.09', '5553.03', '5288.09', '5311.08', '3940.04', '7113.08', '5593.02', '6602.05', '5450.01']
Count of End Stations: 238

Stations appearing in both Start and End:
['11 St & Washington St', '12 St & Sinatra Dr N', '14 St Ferry - 14 St & Shipyard Ln', '2 St & Park Ave', '4 St & Grand St', '4 St & River St', '5 Corners Library', '6 St & Grand St', '7 St & Monroe St', '8 St & Washington St', '9 St HBLR - Jackson St & 8 St', 'Adams St & 12 St', 'Adams St & 2 St', 'Arlington Ave & Bramhall Ave', 'Arlington Ave & Wilkinson Ave', 'Astor Place', 'Baldwin at Montgomery', 'Bergen Ave', 'Bergen Ave & Sip Ave', 'Bergen Ave & Stegman St', 'Bloomfield St & 15 St', 'Brunswick & 6th', 'Brunswick St', 'Carteret Ave & Arlington Ave', 'Christ Hospital', 'Church Sq Park - 5 St & Park Ave', 'City Hall', 'City Hall - Washington St & 1 St', 'Claremont Ave & JFK Blvd', 'Clinton St & 7 St', 'Clinton St & Newark St', 'Columbus Drive', 'Columbus Park - Clinton St & 9 St', 'Communipaw & Berry Lane', 'Communipaw Ave & Pacific Ave', 'Dey St', 'Dixon Mills', 'Dr. Lena Edwards Park', 'Essex Light Rail', 'Exchange Pl', 'Fairmount Ave', 'Garfield Light Rail', 'Glenwood Ave', 'Grand St', 'Grant Ave & MLK Dr', 'Grove St PATH', 'Hamilton Park', 'Harborside', 'Heights Elevator', 'Hilltop', 'Hoboken Ave at Monmouth St', 'Hoboken Terminal - Hudson St & Hudson Pl', 'JC Medical Center', 'Jackson Square', 'Jersey & 3rd', 'Jersey & 6th St', 'Journal Square', 'Lafayette Park', 'Leonard Gordon Park', 'Liberty Light Rail', 'Lincoln Park', 'MLK Dr & Bramhall Ave', 'Madison St & 1 St', 'Mama Johnson Field - 4 St & Jackson St', 'Manila & 1st', 'Marin Light Rail', 'Marshall St & 2 St', 'McGinley Square', 'Monmouth & 6th', 'Monroe St & 11 St', 'Montgomery St', 'Morris Canal', 'Newark Ave', 'Newark St & Washington St', 'Newport PATH', 'Newport Pkwy', 'Oakland Ave', 'Paulus Hook', 'Pershing Field', 'River St & 1 St', 'River St & Newark St', 'Riverview Park', 'South Waterfront Walkway - Sinatra Dr & 1 St', 'Southwest Park - Jackson St & Observer Hwy', 'Stevens - River Ter & 6 St', 'Union St', 'Union St & Bergen Ave', 'Van Vorst Park', 'Warren St', 'Washington St', 'West Side Ave & Stegman Pkwy', 'West Side Ave Light Rail', 'Willow Ave & 12 St', 'York St & Marin Blvd']
Count: 94
Common Station IDs: ['HB101', 'HB103', 'HB105', 'HB106', 'HB201', 'HB202', 'HB203', 'HB301', 'HB302', 'HB303', 'HB304', 'HB305', 'HB401', 'HB402', 'HB404', 'HB407', 'HB408', 'HB409', 'HB501', 'HB502', 'HB505', 'HB508', 'HB601', 'HB602', 'HB603', 'HB608', 'HB609', 'HB610', 'HB611', 'HB612', 'JC002', 'JC003', 'JC006', 'JC008', 'JC009', 'JC013', 'JC014', 'JC018', 'JC019', 'JC020', 'JC022', 'JC023', 'JC024', 'JC027', 'JC032', 'JC034', 'JC035', 'JC038', 'JC051', 'JC052', 'JC053', 'JC055', 'JC057', 'JC059', 'JC063', 'JC065', 'JC066', 'JC072', 'JC074', 'JC075', 'JC076', 'JC077', 'JC078', 'JC080', 'JC081', 'JC082', 'JC084', 'JC093', 'JC094', 'JC095', 'JC097', 'JC098', 'JC099', 'JC102', 'JC103', 'JC104', 'JC105', 'JC107', 'JC108', 'JC109', 'JC110', 'JC115', 'JC116', 'JC117', 'JC118', 'JC119', 'JC120', 'JC121', 'JC122', 'JC123', 'JC124', 'JC125', 'JC127', 'JC131']
Start Only Stations:
[]
Count: 0
Start Only Station IDs: []
End Only Stations:
['10 Ave & W 14 St', '12 Ave & W 40 St', '2 Ave & E 125 St', '2 Ave & E 72 St', '3 Ave & E 71 St', '3 Ave & E 82 St', '3 St & Prospect Park West', '5 Ave & E 30 St', '6 Ave & Broome St', '6 Ave & W 34 St', '6 Ave & W 45 St', '8 Ave & W 16 St', '8 Ave & W 31 St', '8 Ave & W 38 St', '9 Ave & W 18 St', '9 Ave & W 33 St', 'Amsterdam Ave & W 66 St', 'Bleecker St & Crosby St', 'Bridge St & Front St', 'Broad St & Bridge St', 'Broadway & 31 St', 'Broadway & Morris St', 'Broadway & Van Cortlandt Park S', 'Broadway & W 25 St', 'Broadway & W 37 St', 'Broadway & W 38 St', 'Broadway & W 48 St', 'Broadway & W 58 St', 'Bus Slip & State St', 'Canal St & Rutgers St', 'Carmine St & 6 Ave', 'Central Park S & 6 Ave', 'Christopher St & Greenwich St', 'Church St & Worth St', 'Cleveland Pl & Spring St', 'Cliff St & Fulton St', 'Division St & Bowery', 'E 1 St & 1 Ave', 'E 15 St & 5 Ave', 'E 16 St & 5 Ave', 'E 16 St & Irving Pl', 'E 19 St & 3 Ave', 'E 2 St & 2 Ave', 'E 26 St & 3 Ave', 'E 27 St & 1 Ave', 'E 3 St & 1 Ave', 'E 33 St & 5 Ave', 'E 40 St & 5 Ave', 'E 40 St & Park Ave', 'E 43 St & Madison Ave', 'E 44 St & Lexington Ave', 'E 5 St & Cooper Sq', 'E 50 St & Park Ave', 'E 55 St & 2 Ave', 'E 7 St & Ave C', 'E 88 St & 1 Ave', 'East End Ave & E 86 St', 'Fulton St & Broadway', 'Fulton St & William St', 'Grand St & Greene St', 'Greene St & Prince St', 'Greenwich Ave & 8 Ave', 'Greenwich St & Hubert St', 'Greenwich St & W Houston St', 'Harrison St & Hudson St', 'Hudson Blvd W & W 36 St', 'Hudson St & Reade St', 'Hudson St & W 13 St', 'Jay St & Tech Pl', 'LaGuardia Pl & W 3 St', 'Lafayette St & E 8 St', 'Lafayette St & Jersey St', 'Laight St & Hudson St', 'Lawrence St & Willoughby St', 'Leonard St & Church St', 'Liberty St & Broadway', 'Lispenard St & Broadway', 'MacDougal St & Prince St', 'Maiden Ln & Pearl St', 'McKibbin St & Bogart St', 'Mercer St & Bleecker St', 'Mercer St & Spring St', 'Milton St & Franklin St', 'Morton St & Greenwich St', 'Murray St & Greenwich St', 'N 10 St & Berry St', 'N 12 St & Bedford Ave', 'N 15 St & Wythe Ave', 'North Moore St & Greenwich St', 'Old Fulton St', 'Old Slip & South St', 'Park Ave & E 40 St', 'Park Ave & E 41 St', 'Park Ave & E 42 St', 'Pearl St & Whitehall St', 'Pier 40 - Hudson River Park', 'Pier 61 at Chelsea Piers', 'Reade St & Broadway', 'River Ter & Warren St', 'Riverside Dr & W 82 St', 'Sigourney St & Columbia St', 'South St & Gouverneur Ln', 'Spring St & Hudson St', 'Spruce St & Nassau St', 'University Pl & E 14 St', 'University Pl & E 8 St', 'Van Cortlandt Park S & Dickinson Ave', 'Varick St & Watts St', 'Vesey Pl & River Terrace', 'Vesey St & Church St', 'Vesey St & Greenwich St', 'W 16 St & The High Line', 'W 20 St & 5 Ave', 'W 20 St & 8 Ave', 'W 27 St & 6 Ave', 'W 30 St & 10 Ave', 'W 34 St & 11 Ave', 'W 34 St & Hudson Blvd E', 'W 35 St & 9 Ave', 'W 37 St & 10 Ave', 'W 37 St & 5 Ave', 'W 37 St & Broadway', 'W 4 St & 7 Ave S', 'W 42 St & 8 Ave', 'W 44 St & 5 Ave', 'W 48 St &  Rockefeller Plaza', 'W 51 St & 7 Ave', 'W 54 St & 11 Ave', 'W 56 St & 6 Ave', 'W 59 St & 10 Ave', 'W Broadway & Spring St', 'W Broadway & W Houston St', 'Warren St & W Broadway', 'Washington Pl & 6 Ave', 'Washington St & Gansevoort St', 'Washington St & Laight St', 'Water St & Fletcher St', 'Water St & Gouverneur Ln', 'Watts St & Greenwich St', 'West St & Chambers St', 'West St & Liberty St', 'West Thames St', 'William St & Pine St']
Count: 143
End Only Station IDs: {'5450.01', '5137.10', '5610.09', '6955.05', '6190.08', '6441.02', '5470.12', '7149.05', nan, '6960.12', '7235.13', '6022.04', '5492.05', '6432.15', '6779.07', '5772.05', '5788.13', '6072.11', '6578.01', '5175.08', '5561.06', '5065.12', '3865.05', '6876.04', '5653.12', '6157.04', '6551.02', '6948.10', '5033.01', '5712.12', '6569.09', '4903.08', '5329.03', '6611.02', '6765.01', '5288.09', '5679.05', '6535.04', '7023.04', '5359.11', '6098.02', '6459.07', '5288.12', '5679.08', '6173.08', '6464.09', '5763.03', '5137.11', '3940.04', '5520.09', '6611.07', '6432.09', '5391.06', '4710.06', '5359.10', '6364.10', '5947.06', '5593.02', '6659.10', '6215.07', '6925.09', '6526.05', '5593.01', '5553.03', '6450.05', '5755.14', '5880.02', '4889.06', '5696.03', '5602.06', '4953.04', '5297.02', '6089.11', '6248.08', '6233.05', '5247.10', '5532.01', '5470.10', '4993.13', '6115.06', '6593.15', '5450.04', '5644.05', '7154.10', '5065.10', '6398.06', '5721.14', '6233.04', '5905.14', '6039.06', '5539.08', '4968.03', '6626.11', '7113.08', '4962.08', '5105.01', '5545.01', '5359.13', '7648.16', '5303.08', '6492.08', '6809.07', '5500.02', '4993.15', '6004.06', '5114.06', '5216.07', '6708.04', '5539.06', '6322.01', '5216.06', '6602.05', '5509.02', '4596.09', '6551.11', '6789.08', '5730.08', '7388.10', '5938.11', '6474.11', '5938.01', '8879.02', '5024.10', '5752.07', '5569.06', '6650.07', '6224.05', '6441.06', '8859.03', '4962.09', '5838.09', '5368.03', '5578.02', '5311.08', '6072.06', '6560.15', '5065.14', '5184.08', '6432.08', '5847.01', '5400.05', '5059.02', '5687.04', '6432.11'}
Start Stations: 94
End Stations: 237
Common Stations: 94
Start Only Stations: 0
End Only Stations: 143

In [88]:
# No. of Rides which dont have a End Stations specified meaning the Trip was Incomplete
data["end_station_name"].isnull().sum()

np.int64(361)

In [89]:
#Adding a Column in the Dataframe which would be indicator to if the ride was complete or not
data['ride_incomplete'] = data['end_station_name'].isnull()
incomplete_rides = data['ride_incomplete'].sum()

In [90]:
#Which Rides were incomplete and the duration was greater than 2 hours
overlap = (data["ride_incomplete"] & data['duration_outlier']).sum()
print('No. of Rides which were both incomplete and the duration was greater than 2 hours:', overlap)

No. of Rides which were both incomplete and the duration was greater than 2 hours: 58

In [91]:
#Adding a column which would indicate if the ride was from New Jersey to NYC (across River)
data['cross_river_trip'] = (data["end_station_name"].notnull() & (data["end_station_name"].isin(unique_start_stations) == False))
cross_river_trip_count = data['cross_river_trip'].sum()
print ("Cross_river_trip_count = ", cross_river_trip_count)

Cross_river_trip_count =  448

In [92]:
# Adding the Date Column
data["date"]        = data["started_at"].dt.date
# Adding the Hour of the Day Column    
data["hour_of_day"] = data["started_at"].dt.hour 
# Adding which day of the week column but as a code # Monday=0, Tuesday = 1...,Sunday=6
data["day_of_week"] = data["started_at"].dt.dayofweek   
# Name of the Day   
data["day_name"]    = data["started_at"].dt.day_name()     
# Weekday or not
data["is_weekday"]  = data["day_of_week"].isin([0,1,2,3,4])

In [93]:
# HAVERSINE DISTANCE
def haversine_km(lat1, lon1, lat2, lon2):
    """
    Calculates the great-circle distance between two points on Earth using the Haversine formula.
    Parameters:
        lat1, lon1 : Latitude and longitude of the Start Station
        lat2, lon2 : Latitude and longitude of the End Station

    Returns:
        Distance in kilometers.
        Returns NaN wherever any coordinate is NaN.
    """
    R = 6371  # Earth radius in km
    lat1, lon1, lat2, lon2 = map(ny.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
 
    a = ny.sin(dlat / 2)**2 + ny.cos(lat1) * ny.cos(lat2) * ny.sin(dlon / 2)**2
    c = 2 * ny.arcsin(ny.sqrt(a))
 
    return R * c
 
# Only compute where end coordinates exist (trip_incomplete=False)
# For incomplete trips: distance and speed remain NaN

In [94]:
#Adding the Distance Column in the Dataframe which would be the distance between the Start and End Station
data["distance_km"] = ny.where(data["ride_incomplete"],ny.nan,
    ny.round(haversine_km(data["start_lat"],data["start_lng"],data["end_lat"],data["end_lng"]),2))

In [95]:
#Additonally Adding the Speed Column in the Dataframe which would be the speed of the ride in km/h
data["speed_kmh"] = ny.where(data["ride_incomplete"] | (data["duration_min"] <= 0),ny.nan,
    ny.round(data["distance_km"] / (data["duration_min"] / 60), 2))

In [96]:
data[data["speed_kmh"]>=28] #28 is the Capped speed limit for a bike in Jersey City

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,duration_outlier,ride_incomplete,cross_river_trip,date,hour_of_day,day_of_week,day_name,is_weekday,distance_km,speed_kmh
10340,B7C33187DBA9AAFA,electric_bike,2025-09-30 09:57:41.654,2025-09-30 10:00:44.179,Leonard Gordon Park,JC080,Journal Square,JC103,40.745910,-74.057271,...,False,False,False,2025-09-30,9,1,Tuesday,True,1.43,28.22
26943,2F3F41F3B23554CC,electric_bike,2025-09-13 01:29:59.500,2025-09-13 01:32:43.971,Hilltop,JC019,Newark Ave,JC032,40.731169,-74.057574,...,False,False,False,2025-09-13,1,5,Saturday,False,1.43,31.31

In [97]:
#For Round Trips, Adding a Column in the Dataframe which would be indicator to if the ride was a round trip or not
data['round_trip'] = (data["start_station_name"] == data["end_station_name"]) & (data["ride_incomplete"] == False)

In [98]:
#Descriptive Statistics for the Distance Column
data["distance_km"].describe(percentiles=[.25, .5, .75, .85,.90])

count    115568.000000
mean          1.264136
std           0.844437
min           0.000000
25%           0.700000
50%           1.080000
75%           1.630000
85%           1.990000
90%           2.350000
max          25.930000
Name: distance_km, dtype: float64

In [99]:
#Descriptive Statistics for the Speed Column
data['speed_kmh'].describe(percentiles=[.25, .5, .75, .85,.90])

count    115568.000000
mean         10.702448
std           4.612202
min           0.000000
25%           8.110000
50%          10.800000
75%          13.660000
85%          15.290000
90%          16.400000
max          31.310000
Name: speed_kmh, dtype: float64

In [100]:
data['duration_min'].describe(percentiles=[.25, .5, .75, .85,.90])

count    116055.000000
mean         10.744153
std          40.678686
min           1.010000
25%           4.200000
50%           6.470000
75%          10.390000
85%          13.840000
90%          17.230000
max        1499.950000
Name: duration_min, dtype: float64

In [101]:
""" The Data Cleaning and Feature Engineering is now complete. The Data is ready for Analysis."""

' The Data Cleaning and Feature Engineering is now complete. The Data is ready for Analysis.'

In [102]:
data.info()

<class 'pandas.DataFrame'>
Index: 116055 entries, 0 to 116070
Data columns (total 25 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             116055 non-null  str
 1   rideable_type       116055 non-null  str
 2   started_at          116055 non-null  datetime64[us]
 3   ended_at            116055 non-null  datetime64[us]
 4   start_station_name  116055 non-null  str
 5   start_station_id    116055 non-null  str
 6   end_station_name    115694 non-null  str
 7   end_station_id      115694 non-null  str
 8   start_lat           116055 non-null  float64
 9   start_lng           116055 non-null  float64
 10  end_lat             115568 non-null  float64
 11  end_lng             115568 non-null  float64
 12  member_casual       116055 non-null  str
 13  duration_min        116055 non-null  float64
 14  duration_outlier    116055 non-null  bool
 15  ride_incomplete     116055 non-null  bool
 16  cross_river_trip    116055 non-null  bool
 17  date                116055 non-null  object
 18  hour_of_day         116055 non-null  int32
 19  day_of_week         116055 non-null  int32
 20  day_name            116055 non-null  str
 21  is_weekday          116055 non-null  bool
 22  distance_km         115568 non-null  float64
 23  speed_kmh           115568 non-null  float64
 24  round_trip          116055 non-null  bool
dtypes: bool(5), datetime64[us](2), float64(7), int32(2), object(1), str(8)
memory usage: 18.3+ MB

In [103]:
data.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual', 'duration_min', 'duration_outlier', 'ride_incomplete',
       'cross_river_trip', 'date', 'hour_of_day', 'day_of_week', 'day_name',
       'is_weekday', 'distance_km', 'speed_kmh', 'round_trip'],
      dtype='str')

In [104]:
# Saving  the cleaned DataFrame
import os
output_dir = r"C:\Data D\Python_sreejit"
output_path = os.path.join(output_dir, "citibike_tripdata_september_2025_cleaned.csv")
data.to_csv(output_path, index=False)
print(f"File saved successfully at:\n{output_path}")

File saved successfully at:
C:\Data D\Python_sreejit\citibike_tripdata_september_2025_cleaned.csv

In [105]:
data[data['round_trip'] == True]

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,ride_incomplete,cross_river_trip,date,hour_of_day,day_of_week,day_name,is_weekday,distance_km,speed_kmh,round_trip
54,4B052E19F333590D,electric_bike,2025-09-28 11:34:48.462,2025-09-28 11:54:54.409,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046964,...,False,False,2025-09-28,11,6,Sunday,False,0.0,0.0,True
55,BED6D24420BC4E9D,electric_bike,2025-09-27 14:32:46.186,2025-09-27 16:10:35.877,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046964,...,False,False,2025-09-27,14,5,Saturday,False,0.0,0.0,True
56,20EEEA7A5F469232,electric_bike,2025-09-17 17:39:42.834,2025-09-17 17:52:56.967,MLK Dr & Bramhall Ave,JC121,MLK Dr & Bramhall Ave,JC121,40.716470,-74.074130,...,False,False,2025-09-17,17,2,Wednesday,True,0.0,0.0,True
168,84BE79BA7C26B2D1,electric_bike,2025-09-08 11:52:17.584,2025-09-08 11:55:06.416,Claremont Ave & JFK Blvd,JC125,Claremont Ave & JFK Blvd,JC125,40.711890,-74.083850,...,False,False,2025-09-08,11,0,Monday,True,0.0,0.0,True
201,8ABF0BAC54BBB8A8,electric_bike,2025-09-25 19:35:33.613,2025-09-25 19:36:44.920,Glenwood Ave,JC094,Glenwood Ave,JC094,40.727551,-74.071061,...,False,False,2025-09-25,19,3,Thursday,True,0.0,0.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115914,EDD2F66B95BA01AF,classic_bike,2025-09-11 13:47:32.323,2025-09-11 14:00:01.147,11 St & Washington St,HB502,11 St & Washington St,HB502,40.749985,-74.027150,...,False,False,2025-09-11,13,3,Thursday,True,0.0,0.0,True
115917,F0D45C6F3EA3C71D,electric_bike,2025-09-28 11:49:47.512,2025-09-28 12:01:13.684,8 St & Washington St,HB603,8 St & Washington St,HB603,40.745984,-74.028199,...,False,False,2025-09-28,11,6,Sunday,False,0.0,0.0,True
115921,94AC152D2E117344,electric_bike,2025-09-12 07:32:40.090,2025-09-12 07:45:28.724,11 St & Washington St,HB502,11 St & Washington St,HB502,40.749985,-74.027150,...,False,False,2025-09-12,7,4,Friday,True,0.0,0.0,True
115929,4F816DABC0EE602B,electric_bike,2025-09-01 20:37:06.688,2025-09-01 21:35:47.028,8 St & Washington St,HB603,8 St & Washington St,HB603,40.745984,-74.028199,...,False,False,2025-09-01,20,0,Monday,True,0.0,0.0,True
116046,0BC448E2DCBB8689,electric_bike,2025-09-16 14:10:59.335,2025-09-16 14:13:37.765,4 St & River St,HB611,4 St & River St,HB611,40.740814,-74.027406,...,False,False,2025-09-16,14,1,Tuesday,True,0.0,0.0,True

In [106]:
#END OF DATA CLEANING AND FEATURE ENGINEERING

In [107]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\Users\sreej\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.0.51)
Requirement already satisfied: pymysql in c:\Users\sreej\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.2.0)
Requirement already satisfied: greenlet>=1 in c:\Users\sreej\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (3.5.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\sreej\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [108]:
from sqlalchemy import create_engine

In [109]:
print(data.shape)

(116055, 25)

In [110]:

engine = create_engine(
    "mysql+pymysql://root:12345678@127.0.0.1:3306/citibike_trip_data_202509"
)

In [111]:
data

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,ride_incomplete,cross_river_trip,date,hour_of_day,day_of_week,day_name,is_weekday,distance_km,speed_kmh,round_trip
0,3AAD1E1BCB6B326B,electric_bike,2025-09-04 08:36:52.378,2025-09-04 08:47:21.064,Lincoln Park,JC053,Dey St,JC065,40.724605,-74.078406,...,False,False,2025-09-04,8,3,Thursday,True,1.75,10.02,False
1,EC348BE3649505F6,electric_bike,2025-09-08 18:00:44.089,2025-09-08 18:18:48.698,Exchange Pl,JC116,Dey St,JC065,40.716366,-74.034344,...,False,False,2025-09-08,18,0,Monday,True,3.63,12.05,False
2,6639ACBA00F4DC07,classic_bike,2025-09-06 08:59:06.165,2025-09-06 14:27:30.692,Union St & Bergen Ave,JC122,Dey St,JC065,40.715750,-74.078870,...,False,False,2025-09-06,8,5,Saturday,False,2.64,0.48,False
3,A10A50B94E43F61E,classic_bike,2025-09-08 18:11:33.185,2025-09-08 18:17:06.671,Bergen Ave & Sip Ave,JC109,Dey St,JC065,40.731009,-74.064437,...,False,False,2025-09-08,18,0,Monday,True,0.77,8.31,False
4,56D1E808E38A2034,electric_bike,2025-09-24 17:39:37.945,2025-09-24 18:01:08.535,Exchange Pl,JC116,Dey St,JC065,40.716366,-74.034344,...,False,False,2025-09-24,17,2,Wednesday,True,3.63,10.13,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116066,CC1A3434E54DF1BB,electric_bike,2025-09-18 20:41:35.649,2025-09-18 20:44:05.632,Grove St PATH,JC115,Dixon Mills,JC076,40.719410,-74.043090,...,False,False,2025-09-18,20,3,Thursday,True,0.63,15.12,False
116067,5E0DD9F35E2DFDD2,electric_bike,2025-09-16 17:29:31.645,2025-09-16 17:39:11.839,Grove St PATH,JC115,Dixon Mills,JC076,40.719410,-74.043090,...,False,False,2025-09-16,17,1,Tuesday,True,0.63,3.91,False
116068,4BB9B26066FBB751,electric_bike,2025-09-10 20:26:42.519,2025-09-10 20:29:49.038,Marin Light Rail,JC013,Montgomery St,JC099,40.714584,-74.042817,...,False,False,2025-09-10,20,2,Wednesday,True,0.87,16.78,False
116069,78EEB4462A37D488,classic_bike,2025-09-06 23:16:08.972,2025-09-06 23:20:05.770,Grove St PATH,JC115,Dixon Mills,JC076,40.719410,-74.043090,...,False,False,2025-09-06,23,5,Saturday,False,0.63,9.57,False
116070,890297306A2E52C1,electric_bike,2025-09-29 17:44:49.717,2025-09-29 17:47:05.333,Grove St PATH,JC115,Montgomery St,JC099,40.719410,-74.043090,...,False,False,2025-09-29,17,0,Monday,True,0.67,17.79,False

In [112]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:12345678@127.0.0.1:3306/citibike_trip_data_202509"
)

with engine.connect() as conn:
    print("Connected successfully!")

Connected successfully!

In [114]:
data.to_sql(
    name="trip_data",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=10000,
    method="multi"
)

print("Import completed successfully!")

Import completed successfully!

In [122]:
# START STATIONS

start_stations = (
    data[["start_station_id", "start_station_name", "start_lat", "start_lng"]]
    .dropna(subset=["start_station_id", "start_station_name"])
    .drop_duplicates(subset=["start_station_id"])
    .rename(columns={
        "start_station_id"  : "station_id",
        "start_station_name": "station_name",
        "start_lat"         : "lat",
        "start_lng"         : "lng"
    })
    .sort_values("station_name")
    .reset_index(drop=True)
)


start_stations["region"] = start_stations["station_id"].apply(
    lambda x: "Jersey City" if str(x).startswith("JC")
         else "Hoboken" if str(x).startswith("HB")
         else "New York City"
)
start_stations = start_stations.sort_values(["region", "station_name"]).reset_index(drop=True)
 
# 94 unique JC/Hoboken stations — all have complete data

In [124]:

# END STATIONS

end_stations = (
    data[["end_station_id", "end_station_name", "end_lat", "end_lng"]]
    .dropna(subset=["end_station_id", "end_station_name"])
    .sort_values("end_lat", ascending=False)   # non-null lats sort first
    .drop_duplicates(subset=["end_station_id"])
    .rename(columns={
        "end_station_id"  : "station_id",
        "end_station_name": "station_name",
        "end_lat"         : "lat",
        "end_lng"         : "lng"
    })
    .sort_values("station_name")
    .reset_index(drop=True)
)


end_stations["region"] = end_stations["station_id"].apply(
    lambda x: "Jersey City" if str(x).startswith("JC")
         else "Hoboken" if str(x).startswith("HB")
         else "New York City"
)
end_stations = end_stations.sort_values(["region", "station_name"]).reset_index(drop=True)
 
# 237 unique stations — 94 JC + 143 NYC-side cross-river stations
# NYC-side stations have numeric IDs (e.g. 6157.04) vs HB/JC prefix for JC

In [125]:
# Saving the start and end stations to CSV files

start_stations.to_csv("start_stations.csv", index=False)
end_stations.to_csv("end_stations.csv", index=False)
 
print(f"Start stations: {len(start_stations)} unique → start_stations.csv")
print(f"End stations:   {len(end_stations)} unique → end_stations.csv")
print()
print("Start stations sample:")
print(start_stations.head())
print()
print("End stations sample:")
print(end_stations.head())

Start stations: 94 unique → start_stations.csv
End stations:   237 unique → end_stations.csv

Start stations sample:
  station_id                       station_name        lat        lng   region
0      HB502              11 St & Washington St  40.749985 -74.027150  Hoboken
1      HB201               12 St & Sinatra Dr N  40.750604 -74.024020  Hoboken
2      HB202  14 St Ferry - 14 St & Shipyard Ln  40.752961 -74.024353  Hoboken
3      HB608                    2 St & Park Ave  40.739153 -74.033082  Hoboken
4      HB301                    4 St & Grand St  40.742258 -74.035111  Hoboken

End stations sample:
  station_id                       station_name        lat        lng   region
0      HB502              11 St & Washington St  40.749985 -74.027150  Hoboken
1      HB201               12 St & Sinatra Dr N  40.750604 -74.024020  Hoboken
2      HB202  14 St Ferry - 14 St & Shipyard Ln  40.752961 -74.024353  Hoboken
3      HB608                    2 St & Park Ave  40.739153 -74.033082  Hoboken
4      HB301                    4 St & Grand St  40.742258 -74.035111  Hoboken